# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/11-App

# default values
all:
####tmcAdministrationPlugin
  tmcAdministrationPlugin:
    header_title:       Wolna Nuta
    footer_name:        inps
    footer_url:         http://www.inps.pl/
    theme:              darkblue
    theme_web_dir:      ''
    logo_src:           /images/admin/logo.png
    logo_size:          40x40

  sfGuardPlugin:
    header_title:       Wolna Nuta
    footer_name:        inps
    footer_url:         http://www.inps.pl/
    login_logo_src:     /images/admin/logo.png
    login_logo_size:    252x252
    login_logo_title:   'Wolna Nuta'
    login_show_title:   true
    secure_links:       true
    signin_links:       true
    register_links:     true
    forgot_password_links: true

  sf_admin_dash:
    web_dir:                      /tmcAdministrationPlugin
    image_dir:                    /tmcAdministrationPlugin/images/dashboard/
    default_image:                config.png
    resize_mode:                  thumbnail
    logout:                       true
    site:                         Wolna Nuta
    include_path:                 true
    include_jquery_no_conflict:   false
    login_route:                  '@sf_guard_signin'
    logout_route:                 '@sf_guard_signout'

    categories:
      Administracja:
        items:
          Użytkownicy:
            url:          '@sf_guard_user'
            image:        support.png
            credentials:  [administrator]
      CMS:
        items:
          Strony:
            url:          homepage
            image:        support.png
            credentials:  [administrator]
          Comments:
            url:          homepage
            image:        menu.png
            credentials:  [administrator]

####tmcAdministrationPlugin